spring:
  application:
    name: fox-task-manager

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:user}
      password: ${SPRING_SECURITY_USER_PASSWORD:}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: true

  flyway:
    enabled: ${FLYWAY_ENABLED}

server:
  port: ${APP_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration-minutes: ${JWT_ACCESS_EXPIRATION_MINUTES:15}
    refresh-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS:30}

  cookie:
    secure: ${COOKIE_SECURE:false}

  admin:
    login: ${ADMIN_LOGIN}
    password: ${ADMIN_PASSWORD}
    display-name: ${ADMIN_DISPLAY_NAME:Admin}
    email: ${ADMIN_EMAIL:}

  default-user:
    enabled: ${APP_DEFAULT_USER_ENABLED:true}
    login: ${APP_DEFAULT_USER_LOGIN:user}
    password: ${APP_DEFAULT_USER_PASSWORD:}
    display-name: ${APP_DEFAULT_USER_DISPLAY_NAME:user}
    email: ${APP_DEFAULT_USER_EMAIL:}
    update-password: ${APP_DEFAULT_USER_UPDATE_PASSWORD:true}

  telegram:
    bot-username: ${APP_TELEGRAM_BOT_USERNAME}
    bot-token: ${APP_TELEGRAM_BOT_TOKEN}
    return-base-url: ${APP_TELEGRAM_RETURN_BASE_URL:}
    webhook-secret: ${APP_TELEGRAM_WEBHOOK_SECRET:}
    auth-max-age-seconds: ${APP_TELEGRAM_AUTH_MAX_AGE_SECONDS:86400}
